name: "Continuous Integration"

on: push

jobs:
    phpunit:
        uses: dontdrinkandroot/github-actions/.github/workflows/php-symfony-bundle-phpunit.yml@main
        secrets: inherit

    phpstan:
        uses: dontdrinkandroot/github-actions/.github/workflows/php-symfony-bundle-phpstan.yml@main
        secrets: inherit

    sonarcloud:
        uses: dontdrinkandroot/github-actions/.github/workflows/php-sonarcloud.yml@main
        needs: phpunit
        with:
            project-key: 'dontdrinkandroot_api-platform-bundle.php'
        secrets: inherit
